
version: '3'
services:
  telegram-shop:
    image: telegram-shop
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"
  shop-delivery:
    image: shop-delivery
    build: .
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - telegram-shop